llcd_config:
  data_root: /home/pcl/TrainData/dataset/MulRan_processed/Riverside001/
  # data_dir: /home/pcl/TrainData/dataset/MulRan_processed/Riverside001/ouster/
  lidar_data_dir: ouster/
  feature_data_dir: feature/
  data_format: .pcd
  skip_distance: 5

# config for build lidar local map
localmap_config:
  print: false
  distance_gap: 0
  voxel_size: 0.1

  # method list: [point_num, radius, pose_distance, single_frame]
  method: pose_distance
  point_num:
    max_map_point_num: 100000
  radius:
    max_map_radius: 80
  pose_distance:
    max_map_pose_distance: 3


# config for feature extraction
feature_extraction_config:
  print: true
  
  # keyframe pre processing
  use_downsampling: true
  downsampling:
    voxel_size: 0.1
  
  # method list: [point_based]
  method: point_based
  
  # descriptor list: [cvfh]
  descriptors:
    - cvfh
  cvfh:
    normalize_bin: true
    curvature_threshold: 0.7
    normal_search_radius: 0.3
    epsilon_angle_threshold: 5.0


# config for loop detection
loopdetection_config:
  print: false

  # feature list: [histogram, scan_context]
  feature: histogram

  # method list: [opencv_svm, scan_context]
  classifier: opencv_svm
  min_frame_gap: 500

  # opencv_svm classifier
  opencv_svm: 
    model_dir: /home/pcl/dev_home/PycharmProjects/svm_trainer_py/opencv_svm_models/
    model_file: cvfh_uni_svm_dist_norm_th30_multi_origincent_bc_1_rbf_weight_1_5.xml

  # cvfh:[308], [45,45,45,45,128]
  sub_histogram_sizes: [308]
  top_score_num: 32

# config for loop registration
registration_config:
  print: true
  
  # method list: [gicp]
  method: gicp

  gicp:
    fitness_score_threshold: 1.0
    max_correspondence_distance: 100
    max_iterations: 100
